server:
  port: 9000
cloudPlatform:
  requestTimeOut: 5000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: insureusr
    password: insureusr_Kara!
    url: jdbc:mysql://10.19.15.43:39306/kara_insuredb?characterEncoding=UTF-8&useSSL=true
  application:
    name: message
  profiles:
    active: test
  jpa:
#    hibernate:
#      ddl-auto: update
    show-sql: true
    database: mysql
  data:
    mongodb:
      host: 10.19.15.43
      port: 37017
      database: karawebhook
      uri: mongodb://10.19.15.43:37017/karawebhook
heartbeat:
  udpServerList: 127.0.0.1:18080,127.0.0.1:13333
  retryTimes: 3
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/
  instance:
    hostname: message-center
    prefer-ip-address: true
