cloudPlatform:
  requestTimeOut: 5000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/activiti?characterEncoding=UTF-8&useSSL=true
  application:
    name: message_center
server:
  port: 8080