spring:
  application:
    name: cloud_platform-eureka-server
server:
  port: 8000
eureka:
  client:
      service-url:
          defaultZone: http://peer2:8001/eureka/
  instance:
    hostname: peer1