spring:
  application:
    name: cloud-platform-eureka-server
server:
  port: 8000
logging:
  level:
    com: debug
eureka:
  instance:
    #cloud 推荐使用ip方式 http://cloud.spring.io/spring-cloud-static/spring-cloud-netflix/2.0.1.RELEASE/multi/multi_spring-cloud-eureka-server.html
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://peer1:8001/eureka/